[project]
name = "raspberry-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hf-xet>=1.1.3",
    "ollama>=0.5.1",
]
